### ISSUE TITLE
"System.IO.FileLoadException: Could not load file or assembly ..." error shown in NLog tab

### ISSUE THREAD

**Issue by kenny-evitt** [rho24/Glimpse.NLog#11]
Here's the full text shown in that tab (formatted somewhat for readability):

    System.IO.FileLoadException: Could not load file or assembly 'NLog, Version=2.0.1.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c' or one of its dependencies.

    The located assembly's manifest definition does not match the assembly reference.

    (Exception from HRESULT: 0x80131040) File name: 'NLog, Version=2.0.1.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c' at Glimpse.NLog.NLogTab.GetData(ITabContext context) at Glimpse.Core.Framework.GlimpseRuntime.ExecuteTabs(RuntimeEvent runtimeEvent)
    === Pre-bind state information ===
    LOG: User = RECP\taugustine LOG: DisplayName = NLog, Version=2.0.1.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c (Fully-specified) 
    LOG: Appbase = file:///C:/@Kiln/MriApps/Solutions/Mri.Web.Mvc/ 
    LOG: Initial PrivatePath = C:\@Kiln\MriApps\Solutions\Mri.Web.Mvc\bin Calling assembly : Glimpse.NLog, Version=1.3.0.0, Culture=neutral, PublicKeyToken=null. === 
    LOG: This bind starts in default load context. 
    LOG: Using application configuration file: C:\@Kiln\MriApps\Solutions\Mri.Web.Mvc\web.config 
    LOG: Using host configuration file: C:\Users\kevitt\Documents\IISExpress\config\aspnet.config 
    LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config. 
    LOG: Post-policy reference: NLog, Version=2.0.1.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c 
    LOG: Attempting download of new URL file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/Temporary ASP.NET Files/root/d1b5fe9b/5adbda/NLog.DLL. 
    LOG: Attempting download of new URL file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/Temporary ASP.NET Files/root/d1b5fe9b/5adbda/NLog/NLog.DLL. 
    LOG: Attempting download of new URL file:///C:/@Kiln/MriApps/Solutions/Mri.Web.Mvc/bin/NLog.DLL. WRN: Comparing the assembly name resulted in the mismatch: Build Number ERR: Failed to complete setup of assembly (hr = 0x80131040). Probing terminated.

I'm at a loss understanding why it seems to be trying to load version *2.0.1.0* of NLog as version *2.0.0.2000* is installed instead. I couldn't find any explicit references to the former version in any files in my project either.

**Comment by 304NotModified** [comment]
I think this issue can be closed due inactivity?

**Comment by kenny-evitt** [comment]
@304NotModified Sure; I'll add a comment if I ever get around to testing the suggestion (and this is still relevant when I next look at this stuff anyways).
