### ISSUE TITLE
Lower framework target to 4.5.0?

### ISSUE THREAD

**Issue by dnolan** [rho24/Glimpse.NLog#14]
I added this project to my build, but it didn't get picked up as I'm targeting 4.5.0 and the nuget package was against 4.5.1. I've incremented my project to 4.5.1 to be compatible but I wondered if it was necessary to be targeting 4.5.1 by default?

Nice work btw, although could do with some documentation, even if it is as simple as adding the nuget package (which didn't work first time for me due to above issue and a warning rather than an error due to no explicit usage).

**Comment by rho24** [comment]
Hi Daniel
I can't think of any reason why it needs 4.5.1 so as soon as I get a chance I'll give it a go.

**Comment by dnolan** [comment]
Thankyou :+1:

**Comment by rho24** [comment]
Change will be in version 1.6.0, should be live in the next few minutes.
