### ISSUE TITLE
Build to NLog 4

### ISSUE THREAD

**Issue by 304NotModified** [rho24/Glimpse.NLog#18]
Is see the plugin is build to an old version of NLog. I would recommend to build this to NLog 4.0.0. 

Since NLog 4.0.0 the assembly version is stable so you can use NLog 4.x.y without any assembly redirect.

**Comment by rho24** [comment]
Sounds sensible to me, glad to see they've simplified their assembly versioning.

I'll try and get to it in the next couple of weeks. I'd also be more than happy to merge a pull request if you'd like to give it a go yourself.
