### ISSUE TITLE
Option to view the entire log instead of only the messages associated with the last request

### ISSUE THREAD

**Issue by rlenders** [rho24/Glimpse.NLog#22]
I was hoping I could use this Glimpse tab to view logs without having to download the log files from my web server. However, this tab only allows you to see log messages associated with a single request. Please make an option so we can see the entire log, similar to how Glimpse.Elmah shows the entire error history.

**Comment by rho24** [comment]
Hi rlenders, sorry for the late reply.
I don't plan to add this option to Glimpse.Nlog as there is no global store for all log messages in NLog and I'm not prepared to add one to this.

If you have any suggestions on how this couple be implemented without a global store in Glimpse.Nlog, feel free to comment again and I'll re-open.
