### ISSUE TITLE
An unhandled exception of type 'System.StackOverflowException' occurred in Glimpse.AspNet.dll

### ISSUE THREAD

**Issue by prainho** [rho24/Glimpse.NLog#23]
I think you should read this issue https://github.com/Glimpse/Glimpse/issues/993 that I open in glimpse because I think this trace should be removed

try
        {
            timer = _timerStrategy();
        }
        catch (Exception e)
        {
            **Trace.Write(e.ToString());**
        }

And I think this is causing System.StackOverflowException when exceptions happen in _timerStrategy() and when using NLog.NLogTraceListener in system.diagnostics section in web.config

**Comment by prainho** [comment]
Can you please just comment that trace that is causing System.StackOverflowException? when using NLog.NLogTraceListener in system.diagnostics section in web.config

**Comment by rho24** [comment]
Hi @prainho, apologies, I haven't touched this project for a while. I'll try to get time this weekend to get a new version out with your fix.

**Comment by rho24** [comment]
Hi @prainho, version 1.7.1 has now been published to nuget.
